// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVJ16ZoDO6_vm7BKdpgNqnl-ihWCumyYI',
    appId: '1:451508829773:web:2b7edc72198af24cd56604',
    messagingSenderId: '451508829773',
    projectId: 'quickbite-17a39',
    authDomain: 'quickbite-17a39.firebaseapp.com',
    storageBucket: 'quickbite-17a39.appspot.com',
    measurementId: 'G-W5LWZVNNE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFCQohkJsjzQMf7vCFO48uNhKAl8Wx70I',
    appId: '1:451508829773:android:3f529287b9937539d56604',
    messagingSenderId: '451508829773',
    projectId: 'quickbite-17a39',
    storageBucket: 'quickbite-17a39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW5kHj7DQLD9WQcuDDrBAjOAV0FH0A50g',
    appId: '1:451508829773:ios:857a9776ef6638aad56604',
    messagingSenderId: '451508829773',
    projectId: 'quickbite-17a39',
    storageBucket: 'quickbite-17a39.appspot.com',
    iosBundleId: 'com.example.quickbite',
  );
}
